/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package mozilla.components.concept.llm

/**
 * A tool a feature makes available to the model. When the model decides to call the tool,
 * the session executes [invoke] and feeds the result back to the model, hiding the
 * round-trip from consumers of [LlmSession.send].
 *
 * Mirrors the shape of function-calling tools in emerging agent standards.
 */
interface LlmTool {
    /** The name the model uses to reference this tool. */
    val name: String

    /** A natural-language description telling the model when and why to call the tool. */
    val description: String

    /**
     * A JSON Schema string describing the tool's parameters. The model generates
     * [invoke] arguments conforming to this schema. May be `null` for tools that take
     * no arguments.
     */
    val parametersSchema: String?

    /**
     * Executes the tool.
     *
     * @param arguments The arguments generated by the model, keyed by parameter name.
     * @return The tool's result, keyed for the model to consume.
     */
    suspend fun invoke(arguments: Map<String, Any?>): Map<String, Any?>
}
